### PR TITLE
Use govuk_template rather than slimmer

### PR DESCRIPTION
**Pull request by edds**
So that trade tariff isn't accidentally changed as a result of assets being updated in static use govuk_template instead of slimmer.

The main change for users of this change is that it looses the search box in the header, the report a problem box and the GOV.UK service and information links from the footer.

Otherwise I believe it now replicates the current functionality as in on production.

### CODE REVIEW

**Comment by bradleywright** [comment]
Happy with the code and the intent behind them - making tariff more of an island is a sensible change.

I'd like @marksheldonGDS to take a look over the functional changes and make sure he's happy with them before we merge this though.

**Comment by marksheldonGDS** [comment]
Reviewed the changes with @edds and agreed they're all fine. If there's any way we can keep the "Is there anything wrong with this page?" form that would be good.

**Comment by bradleywright** [comment]
After you're happy with the latest changes @marksheldonGDS please merge this.

**Comment by marksheldonGDS** [comment]
Reviewed and accepted :+1:

**Comment by bradleywright** [comment]
Thanks @marksheldonGDS

**Comment by matthewford** [comment]
@marksheldonGDS @edds seems it did not build on Jenkins

**Pull request merged**
